apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "kubeconfig.clustar.ai"
spec:
  group: "clustar.ai"
  version: "v1"
  scope: "Namespaced"
  names:
   plural: "kubeconfigs"
   singular: "kubeconfig"
   kind: "Kubeconfig"
 validation:
   openAPIV3Schema:
     required: ["spec"]
     properties:
       spec:
         required: ["serviceAccount"]
         properties:
           replicas:
             type: "string"